### PR TITLE
rawMismatch + fix tests

### PR DESCRIPTION
**Pull request by darkartur**

### CODE REVIEW

**Comment by mirzazeyrek** [comment]
Hello @darkartur,

Thank you for your PR. Is it possible if you could close this one and send all the related changes in 1 commit based from latest version of original master branch ?

**Comment by lksv** [comment]
Hi,
Thank you for this PR too. It's perfect. I would prefer to keep following three commits as is:

  |  Ignore JetBrains IDE files | c44816d
  |  rawMisMatchPercentage feature | da497ea
  |  Fix initial color for diff | 1fddc71

(e.g. not to sqash them together). Because they fixes/implements individual features.

But please remove commits  aa3f862 and 5f278a5. You can do it by `git reset --hard 1fddc7123bd2f53e465f3a1cbdcf0d3a9d30533a; git push -f` in your foked master.

**Comment by darkartur** [comment]
Done

**Comment by darkartur** [comment]
Guys?

**Comment by z-vr** [comment]
hello @mirzazeyrek @lksv do you mind merging the PR pleas?

**Comment by mirzazeyrek** [comment]
Merged. Thank you.

**Comment by darkartur** [comment]
@mirzazeyrek @lksv can u please publish new version to NPM?

**Comment by mirzazeyrek** [comment]
@lksv Can we update npm ?

**Pull request merged**
